# Generated by Django 4.2.3 on 2023-07-23 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qrCodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
