# Generated by Django 4.2.3 on 2023-07-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrCodes', '0004_alter_qrcode_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='url',
            field=models.CharField(max_length=250),
        ),
    ]
